# Site settings
title:       Duarte Bruno
author:      Bruno Duarte
description: "Meu site pessoal."
baseurl:     ""
url:         "https://duartebruno.netlify.com"

# Social Links
email:            brunopereiras@icloud.com
twitter_username:
github_username:  brunopereiras

# Build settings
markdown: kramdown
permalink: pretty
